### ISSUE TITLE
AsyncLazy broken after rapid cancellation loop

### ISSUE THREAD

**Issue by mjameson-se** [dotnet/dotNext#183]
I had a bug in my code where I was creating a cancellation token with a zero timeout and passing this to an async lazy, which would promptly throw an OperationCancelledException as you might expect. However after many iterations of this, I started getting a different exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'function')
   at System.Threading.Tasks.Task.Run[TResult](Func`1 function, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Run[TResult](Func`1 function)
   at DotNext.Threading.AsyncLazy`1.GetOrStartAsync(CancellationToken token) in /_/src/DotNext.Threading/Threading/AsyncLazy.cs:line 101
```
This AsyncLazy was non-resettable, so I think its safe to assume the change has something to do with `EraseFactory`

**Comment by sakno** [comment]
Do you have repro code?
